version: "3.5"
services:
  artalk: #评论系统1
    container_name: artalk
    image: artalk/artalk-go
    restart: always
    ports:
      - 8181:23366
    volumes:
      - ./data/artalk:/data
  twikoo: #评论系统2
    container_name: twikoo
    image: imaegoo/twikoo
    restart: always
    environment:
      TWIKOO_THROTTLE: 1000
    ports:
      - 8182:8080
    volumes:
      - ./data/twikoo:/data
  # meting: #自建音乐api
  #   container_name: meting-api
  #   image: intemd/meting-api:latest
  #   restart: always
  #   ports:
  #     - 8183:3000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  alist:
      restart: always
      volumes:
          - './alist:/opt/alist/data'
      ports:
           - '5244:5244'
      environment:
           - PUID=0
           - PGID=0
           - UMASK=022
      image: xhofe/alist:latest 